-- 코드를 입력하세요
# 2. 그룹화한 PRICE를 TRUNCATE함수를 이용하여 4자리수까지 버림, PRICE_GROUP으로 분할되어 있는 PRODUCTS별 총 개수 산출
SELECT TRUNCATE(PRICE,-4) AS PRICE_GROUP, COUNT(*) AS PRODUCTS
FROM PRODUCT
# 1. PRICE_GROUP으로 그룹화
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP