-- 코드를 입력하세요
# 3. 매출액 환산
SELECT PRODUCT_CODE, sum(P.PRICE * O.SALES_AMOUNT) as SALES
# 1. PRODUCT와 OFFLINE 테이블 PRODUCT_ID를 이용한 JOIN
from PRODUCT P join OFFLINE_SALE O on P.PRODUCT_ID = O.PRODUCT_ID
# 2. PRODUCT_CODE로 그룹화
group by PRODUCT_CODE
order by SALES desc, PRODUCT_CODE